<?php
$htmlId = $block->getBannerItemHtmlId();
$bannerCollection = $block->getBannerCollection();
?>
<div class="test-banner slider ">
    <style>
        .custom-navigation {
            display: table;
            width: 100%;
            table-layout: fixed;
        }

        .custom-navigation > * {
            display: table-cell;
        }

        .custom-navigation > a {
            width: 50px;
        }

        .custom-navigation .flex-next {
            text-align: right;
        }
    </style>
    <script type="text/javascript">
        require(['jquery', 'test/flexslider'], function ($) {
            debugger;
            $(document).ready(function ($) {
                var flexSliderSelector = '<?= $htmlId; ?>';
                $('.' + flexSliderSelector).flexslider({
                    animation: "slide",
                    controlsContainer: $(".custom-controls-container"),
                    customDirectionNav: $(".custom-navigation a")
                });
            });
        });
    </script>
    <div class="test-banner-slider">
        <div id="<?= $htmlId ?>" class="flexslider flexslider-content-image <?= $htmlId ?>"
             style="margin:auto">
            <ul class="slides">
                <?php foreach ($bannerCollection as $banner): ?>
                    <li>
                        <a href="<?= $banner->getUrl() ?>"  >
                            <img alt="<?= $banner->getName() ?>"
                                 src="<?= $block->getBannerImageUrl($banner) ?>"
                                 />
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
        <div class="custom-navigation">
            <a href="#" class="flex-prev">Prev</a>
            <div class="custom-controls-container"></div>
            <a href="#" class="flex-next">Next</a>
        </div>
    </div>
</div>
