<h1> Module Learning JS</h1>

<div class="block" data-mage-init='{"hello": {"message": "MODULE JS SAMPLE TEXT!"}}'>
    Click here
</div>

<style type="text/css">
    div.block:hover{color: #8b0000;}
</style>

<div class="field">
    <label>Date : </label>
    <input type="text" class="input-text" id="example-date" style="width: auto" name="example-date" />
</div>


<!--Ajax example-->

<div class="row clearfix">
    <div class="col-md-12 column">
        <form name="form_value" method="POST" id="form_value">
            <label>Number one</label>
            <input type="text" name="numone" class="form-control input-md"

                   style="margin:20px;width:300px;" autocomplete="off">
            <label>Number two</label>
            <input type="text" name="numtwo" class="form-control input-md"

                   style="margin:20px;width:300px;" autocomplete="off">
            <input type="submit" id="calculateTotalS
            ubmit"  name="calculate-total-submit"

                   value="Calculate Total">
    </div>
    </form><br/><br/>
    Result<div class="result" style="display:none"></div>
</div>
</div>


<script>
    require(['jquery'],function(){
        jQuery(document).ready(function() {
            jQuery(".result").hide();
            jQuery("#form_value").submit(function(){
                var oneValue = jQuery("input[name='numone']").val();
                var twoValue = jQuery("input[name='numtwo']").val();

                var url = "<?php echo $block->getBaseUrl().'learnjs/result/result/' ?>";

                jQuery.ajax({
                    url: url,
                    type: "POST",
                    data: {numone:oneValue,numtwo:twoValue},
                    showLoader: true,
                    cache: false,
                    success: function(response){
                        console.log(response.output);
                        jQuery(".result").show();
                        jQuery(".result").text(response.output);
                    }
                });
                return false;
            });
        });
    });
</script>
