<?php

$additionalClass = $block->getAdditionalClass();
$htmlId = $block->getBannerItemHtmlId();
$bannerCollection = $block->getBannerCollection();
?>
<div class="test-banner all-image <?= $additionalClass ?>">
    <div class="test-banner-slider">
        <div id="<?= $htmlId ?>" class="flexslider flexslider-content-image <?= $htmlId ?>"
             style="margin:auto">
            <ul class="slides">
                <?php foreach ($bannerCollection as $banner): ?>
                    <li class="all-image">
                        <a href="<?= $banner->getBannerUrl() ?>"
                           <?= $banner->getTarget() ? 'target="_blank" ' : ''; ?>style="display:block;">
                            <img alt="<?= $banner->getTitle() ?>"
                                 src="<?= $block->getBannerImageUrl($banner) ?>"
                                 title="<?= $banner->getDescription() ?>"/>
                        </a>
                        <?php if ($banner->getDescription()) : ?>
                            <p class="flex-caption"><?= $banner->getDescription() ?></p>
                        <?php endif; ?>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
</div>
